# Generated by Django 3.2.7 on 2024-02-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_job_multipleimage_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agroforest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('trees', models.CharField(max_length=200)),
                ('people', models.CharField(max_length=200)),
                ('acres', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
