# Generated by Django 3.2.7 on 2024-02-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_agroforest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agroforest',
            name='acres',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='agroforest',
            name='people',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='agroforest',
            name='trees',
            field=models.IntegerField(),
        ),
    ]
