# Generated by Django 3.2.7 on 2021-09-11 10:36

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210602_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=72, size=[1920, 1080], upload_to='posts/featured_images'),
        ),
    ]
